import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";
import { homedir } from "os";
import { join, dirname } from "path";

const FEEDBACK_FILE = join(homedir(), ".rn-ai-debugger", "feedback.json");

interface FeedbackConfig {
    feedbackHintShown: boolean;
}

function readFeedbackConfig(): FeedbackConfig {
    try {
        if (!existsSync(FEEDBACK_FILE)) return { feedbackHintShown: false };
        const data = readFileSync(FEEDBACK_FILE, "utf-8");
        return JSON.parse(data) as FeedbackConfig;
    } catch {
        return { feedbackHintShown: false };
    }
}

function writeFeedbackConfig(config: FeedbackConfig): void {
    try {
        const dir = dirname(FEEDBACK_FILE);
        if (!existsSync(dir)) {
            mkdirSync(dir, { recursive: true });
        }
        writeFileSync(FEEDBACK_FILE, JSON.stringify(config, null, 2));
    } catch {
        // Best-effort — silent fail
    }
}

export function shouldShowFeedbackHint(): boolean {
    return !readFeedbackConfig().feedbackHintShown;
}

export function markFeedbackHintShown(): void {
    const config = readFeedbackConfig();
    config.feedbackHintShown = true;
    writeFeedbackConfig(config);
}

// ============================================================================
// Issue Formatting
// ============================================================================

const GITHUB_REPO = "igorzheludkov/react-native-ai-devtools";

interface FeedbackInput {
    type: "feedback" | "feature_request" | "bug";
    title: string;
    description: string;
    workflowContext?: string;
}

interface EnvironmentInfo {
    serverVersion: string;
    platform: string;
    deviceType: string | undefined;
    licenseTier: string;
}

export function formatIssueBody(input: FeedbackInput, env: EnvironmentInfo): string {
    const lines: string[] = [];

    lines.push("## Feedback");
    lines.push(input.description);
    lines.push("");
    lines.push("## Workflow Context");
    lines.push(input.workflowContext || "N/A");
    lines.push("");
    lines.push("## Environment");
    lines.push("| Key | Value |");
    lines.push("|-----|-------|");
    lines.push(`| Server Version | ${env.serverVersion} |`);
    lines.push(`| Platform | ${env.platform} |`);
    lines.push(`| Device | ${env.deviceType || "not connected"} |`);
    lines.push(`| License | ${env.licenseTier} |`);
    lines.push("");
    lines.push("---");
    lines.push(`*Generated by react-native-ai-devtools v${env.serverVersion} via \`send_feedback\`*`);

    return lines.join("\n");
}

export function buildGitHubUrl(title: string, type: FeedbackInput["type"]): string {
    const labelMap: Record<FeedbackInput["type"], string> = {
        bug: "bug",
        feature_request: "enhancement",
        feedback: "feedback",
    };
    const label = labelMap[type];
    const params = new URLSearchParams({
        title,
        labels: label,
    });
    return `https://github.com/${GITHUB_REPO}/issues/new?${params.toString()}`;
}
